FROM node:18
# 작업 디렉토리 설정
WORKDIR /app
# 패키지 파일 복사 및 의존성 설치        
COPY package*.json ./
RUN npm install
# 애플리케이션 소스 복사
COPY . .
# 환경 설정
ENV NODE_ENV=development
# 마이그레이션, 시딩 후 서버 실행
CMD ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && npx prisma db seed && npx nx serve api"]