FROM node:18

WORKDIR /app

# 의존성 설치
COPY package*.json ./
RUN npm install

# 앱 소스 복사
COPY . .

# 개발 서버 환경
ENV PORT=4100
ENV HOST=0.0.0.0
ENV CHOKIDAR_USEPOLLING=true

EXPOSE 4100

# 개발 서버 실행
CMD ["npm", "start"]